version: "3"
networks:
    internal:

services:
    web-app:
        build:
            context: frontend
            dockerfile: Dockerfile
        environment:
            PORT: "5000"
            TIMEOUT: "120"
        ports:
            - "5000:5000"
        networks:
            - internal

        depends_on:
            credit-risk-app:
                condition: service_started

    credit-risk-app:
        build:
            context: backend
            dockerfile: Dockerfile
        environment:
            PORT: "5001"
            DB_USER: "postgres"
            DB_PASSWORD: "zxcvb12345"
            DB_HOST: "database"
            DB_NAME: "postgres"
            TIMEOUT: "120"
        ports:
            - "5001:5001"
        networks:
            - internal
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_PASSWORD: "zxcvb12345"

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 100
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - "5433:5432"
        networks:
            - internal
